services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api
    depends_on:
      postgres: { condition: service_healthy }
      keycloak: { condition: service_started }
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DATABASE_URL: ${POSTGRES_URL}
      KC_BASE_URL: http://keycloak:8080
      KC_PUBLIC_URL: ${KC_HOSTNAME}
    networks:
      - default
      - small-sprint

  postgres:
    image: postgres:16-alpine
    container_name: nest_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - default
      - small-sprint

  keycloak-postgres:
    image: postgres:16-alpine
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: ${KC_POSTGRES_DB}
      POSTGRES_USER: ${KC_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KC_POSTGRES_PASSWORD}
    volumes:
      - 'kc_pg_data:/var/lib/postgresql/data'
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - default

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_local
    command: start-dev
    depends_on:
      keycloak-postgres: { condition: service_healthy }
    restart: unless-stopped
    ports:
      - '8081:8080'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/${KC_POSTGRES_DB}
      KC_DB_USERNAME: ${KC_POSTGRES_USER}
      KC_DB_PASSWORD: ${KC_POSTGRES_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HOSTNAME_STRICT: 'false'
      KC_HEALTH_ENABLED: 'true'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'exec 3<>/dev/tcp/127.0.0.1/9000; printf "GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n" >&3; cat <&3 | grep -q "200 OK"',
        ]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
    networks:
      - default
      - small-sprint

networks:
  default:
  small-sprint:
    external: true

volumes:
  pg_data:
  kc_pg_data:
